name = "hex-mv-poly"
defaultTargets = ["HexMvPoly"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "365881fb205210e8d27c5eb011f7ddb3fe020373"

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "104a2b0c00eedf0ecab222c1a977dd53dbaa9bb3"

[[lean_lib]]
name = "HexMvPoly"
globs = [
  "HexMvPoly",
  "HexMvPoly.Mono",
  "HexMvPoly.Basic",
  "HexMvPoly.Operations",
  "HexMvPoly.Query",
  "HexMvPoly.Eval",
  "HexMvPoly.Structural",
  "HexMvPoly.Recursive",
]

[[lean_lib]]
name = "HexMvPolyTests"
globs = ["HexMvPoly.KernelTests"]
