name = "hex-mv-poly"
defaultTargets = ["HexMvPoly"]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "5354a7153ade8a60effaf6431bda7af22cc3410f"

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "6dcec6053c715ffd47c95e5224692bead4f878db"

[[lean_lib]]
name = "HexMvPoly"

[[lean_lib]]
name = "HexMvPolyTests"
globs = ["HexMvPoly.KernelTests"]
