name = "hex-mv-poly"
defaultTargets = ["HexMvPoly"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a3ab4fd9a79efbe6b07337836b3b5828d22d65a6"

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "069aaf4c0ebd966306f3254d7a180586f9ab893f"

[[lean_lib]]
name = "HexMvPoly"
globs = [
  "HexMvPoly",
  "HexMvPoly.Mono",
  "HexMvPoly.Basic",
  "HexMvPoly.Operations",
  "HexMvPoly.Query",
  "HexMvPoly.Eval",
  "HexMvPoly.Structural",
  "HexMvPoly.Recursive",
]

[[lean_lib]]
name = "HexMvPolyTests"
globs = ["HexMvPoly.KernelTests"]
